### ISSUE TITLE
Add [SOURCE] example to Terms

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/html-pub#41] opened 2022-12-01 19:31 UTC
As per ISO Directive and AG04:

```
16.5.10 Source
If a terminological entry is reproduced from another document, the source shall be given at the end of
the entry. If any changes are made to the original terminological entry, this shall be indicated, along
with a description of what has been modified. A document given as a source of a terminological entry
is informative. Within a terminological entry, cross-references can also be made to terms defined
elsewhere.
EXAMPLE
3.1.2
terminological entry
part of a terminological data collection which contains the terminological data (3.1.3) related to one concept (3.2.1)
Note 1 to entry: A terminological entry prepared in accordance with the principles and methods given in ISO 704 follows
the same structural principles whether it is monolingual or multilingual.
[SOURCE: ISO 1087-1:2000, 3.8.2, modified — Note 1 to entry has been added.]
```

**Comment by palemieux** [comment] 2023-02-15 04:40
Duplicate of #99

**Closed by palemieux** 2023-02-15 04:40 UTC
