### ISSUE TITLE
Annexes A and B: Normative/Informative should be bold

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#221] opened 2024-02-01 17:17 UTC
In the Annex A and B headings, "Normative" and "Informative", respectively, should be bold:
![image](https://github.com/SMPTE/st429-16/assets/118845840/aaf9a67d-2b03-4c70-8430-d4ae7016c316)
![image](https://github.com/SMPTE/st429-16/assets/118845840/a8680787-4911-477f-a092-89977801f65e)

Also, if conforming with ISO, then the headings should be formatted as follows, and centered, as shown in this screen grab from ST 2095-1 (about to be published):
![image](https://github.com/SMPTE/st429-16/assets/118845840/a8e341e3-6f07-4ac3-bb40-7ee4f99ffda8)

Some documents use uppercase first letter for "Normative" and "Informative", and others do not. It would be good to standardize how headings, captions, and table headers are written. Or we can continue to leave it to the author.

**Comment by SteveLLamb** [comment] 2024-05-23 19:46
Duplicate of https://github.com/SMPTE/html-pub/issues/202, as this is auto generated.

**Closed by SteveLLamb** 2024-05-23 19:46 UTC
