### ISSUE TITLE
New Appendix Heading

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#119] opened 2023-06-19 20:56 UTC
Per the HO, we will adopt the ISO Appendix heading. Example:

                                                                    Appendix A
                                                              (Normative/Informative)

                                                                  Appendix Name

All 14 pt Arial Bold, including the empty line. All horizontally centered. Not sure why GitHub changed the font. 

This heading format might present a challenge when creating a Table of Contents.

Also, we have not come to an agreement as to how uppercase and lowercase should be used in headings, captions, and table headers,. Currently, it is author's choice.

Subclause numbering stays the same as it is now.

**Comment by SteveLLamb** [comment] 2024-05-23 20:32
Duplicate of https://github.com/SMPTE/html-pub/issues/202

**Closed by SteveLLamb** 2024-05-23 20:32 UTC
