### ISSUE TITLE
Table Caption Headroom Too large

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#204] opened 2024-01-15 20:17 UTC
There is a large amount of space above the table caption. I recommend shrinking it to sentence spacing.

**Comment by SteveLLamb** [comment] 2024-05-23 19:49
@ERyan71258 is this a duplicate of https://github.com/SMPTE/html-pub/issues/242?

**Comment by SteveLLamb** [comment] 2024-05-23 19:58
Closed as duplicate.

**Closed** 2024-05-23 19:57 UTC
Labels: question
