### ISSUE TITLE
Headers (PDF Only): Missing Date from Document Number

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/html-pub#208] opened 2024-01-24 18:27 UTC
The date is missing from the document number in the headers. Example:
![image](https://github.com/SMPTE/html-pub/assets/118845840/d01fa844-de7d-40a2-96db-d9ed73355e3c)

**Comment by SteveLLamb** [comment] 2024-05-23 19:48
This is duplicate of https://github.com/SMPTE/html-pub/issues/207

**Closed by SteveLLamb** 2024-05-23 19:48 UTC
